server { 
    listen 80;
    server_name localhost;

    # 1. LA PIEZA QUE FALTABA: Aquí servimos los archivos visuales de tu página (Vite/React/Vue)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. Puente a tu API de Ventas
    location /api/v1/ventas {
        # ¡OJO! Asegúrate de que esta sea la IP Privada ACTUAL de tu Backend
        proxy_pass http://10.0.4.54:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 3. Puente a tu API de Despacho
    location /api/v1/despacho {
        # ¡OJO! Asegúrate de que esta sea la IP Privada ACTUAL de tu Backend
        proxy_pass http://10.0.4.54:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
