name: CI/CD ECR Pipeline

on:
  push:
    branches:
      - deploy #El pipeline se activa solo en esta rama.
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Se agregan 2 lineas de código ya que github envió una alerta de deprecado de node 20
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      #1. Autenticarse con AWS usando Secrets
      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} #Obligatorio para academy
          aws-region: us-east-1

      #2.Iniciar sesión en ECR
      - name: Login en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 3. Construir, etiquetar y subir las imágenes a ECR
      - name: Construir y subir Venta
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: innova-venta
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./back-Ventas_SpringBoot/Springboot-API-REST
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Construir y subir Despacho
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: innova-despacho 
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Construir y subir Frontend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: innovatech-frontend 
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./front_despacho
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
      # 4. Desplegar en la instancia EC2
      - name: Desplegar en EC2 Backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          # 1. LA IP DE DESTINO (Tu Backend Privado)
          host: ${{ secrets.EC2_BACKEND_IP }} # Debes crear este secreto con la IP Privada del backend (empieza con 10. o 172.)
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          
          # 2. EL PUENTE (Tu Frontend Público)
          proxy_host: 34.226.123.180 # La IP pública que sale en tu segunda foto
          proxy_username: ec2-user
          proxy_key: ${{ secrets.EC2_SSH_KEY }} # Usa la misma llave .pem
          
          envs: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN, AWS_REGION
          script: |
            cd /home/ec2-user/backend-innovatech
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}
            docker-compose pull
            docker-compose up -d
